FROM node:16-bullseye-slim

WORKDIR /app

# app service SSH config
COPY sshd_config /etc/ssh

RUN mkdir -p /tmp \
    && mkdir -p /apps

COPY ssh_setup.sh /tmp
RUN chmod +x /tmp/ssh_setup.sh \
    && (sleep 1;/tmp/ssh_setup.sh 2>&1 > /dev/null)
# end SSH config

COPY . .

ENTRYPOINT [startup.sh]