FROM node:16-bullseye-slim

WORKDIR /app

# app service SSH config
RUN apt-get update && apt-get install -y openssh-server \
     && echo "root:Docker!" | chpasswd

COPY sshd_config /etc/ssh

RUN mkdir -p /tmp
COPY ssh_setup.sh /tmp
RUN chmod +x /tmp/ssh_setup.sh \
    && (sleep 1;/tmp/ssh_setup.sh 2>&1 > /dev/null)
# end SSH config

COPY . .

RUN npm install
RUN chmod +x startup.sh

EXPOSE 80 2222

ENTRYPOINT ["/app/startup.sh"]